[Database]
server = wbdbserver
database = flute_data

[Email]
to = sang.n@whitebird.ca
cc = 
send_empty_report = False
allow_resend_same_day = False

[Tracking]
# last_sent_date = Automatically updated when email is sent

